<?php
$ves = $this->helper("Ves\Themesettings\Helper\Theme");
$data = $this->helper("Ves\Themesettings\Helper\Data");
$enable_coppyright = $ves->getFooterCfg("general_settings/enable_coppyright");
$enable_custom_coppyright = $ves->getFooterCfg("general_settings/enable_custom_coppyright");
$custom_coppyright = $data->filter($ves->getFooterCfg("general_settings/custom_coppyright"));

?>
<?php if($enable_coppyright){ ?>
<div class="copyright">
 <?php if($enable_custom_coppyright){ ?>
 <?php echo $custom_coppyright; ?>
 <?php }
 else{ ?> 
 <div class="page-main">
    <div class="footer-categories col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('micmart_footer_categories')->toHtml();?>
    </div>
    <div class="copyright-text col-lg-12 col-md-12 col-sm-12 col-xs-12">
    	<span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
    </div>
 </div>
 <?php } ?>    
</div>
<?php } ?>