<?php
$ves = $this->helper('Ves\Themesettings\Helper\Theme');
$max_width = $ves->getGeneralCfg("general_settings/max_width");
$max_width_custom = $ves->getGeneralCfg("general_settings/max_width_custom");
$fluid_width = $ves->getGeneralCfg("general_settings/fluid_width");
?>
<?php if($ves->getGeneralCfg("general_settings/paneltool")){ ?>
<style type="text/css">
<?php
// LAYOUT
if($max_width && !$fluid_width && $max_width){ ?>
.navigation, .page-header .header.panel, .header.content, .footer.content, .page-wrapper > .widget, .page-wrapper > .page-bottom, .block.category.event, .top-container, .page-main {
<?php if($max_width == 'custom'){ ?>
max-width: <?php echo $max_width_custom; ?>;
<?php }else{ ?>
max-width: <?php echo $max_width; ?>;	
<?php } ?>
}
<?php } ?>
<?php if($fluid_width){  ?>
.navigation, .page-header .header.panel, .header.content, .footer.content, .page-wrapper > .widget, .page-wrapper > .page-bottom, .block.category.event, .top-container, .page-main {
padding:0; 
margin:0;
max-width: 100%;
}
<?php } ?>
</style>
<?php } ?>