<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$ves = $this->_ves;
$vesData = $this->_vesData;
$html = '';
$id = $block->getIdModifier() ? '-' . $block->getIdModifier() : time().rand();
?>

<div class="header-links" id="header-links<?php echo $id?>">
        <?php if($vesData->isLoggedIn()){ ?>
        <?php
        $postData = $vesData->getObjectManager()->create('Magento\Framework\Data\Helper\PostHelper');
        $logoutData = $postData->getPostData($block->getUrl('customer/account/logout/'));
        $dataPostParam = sprintf(" data-post='%s'", $logoutData);
        ?>
            <div class="dropdown">
                <div class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-user">&nbsp;</i> <span> <?php echo __('My Account') ?></span> 
                </div>
                <div class="dropdown-menu" role="menu">
                    <ul>
                        <li><a href="<?php echo $block->getUrl('customer/account/edit'); ?>"><?php echo __('Account Information') ?></a></li>
                        <li><a href="<?php echo $block->getUrl('sales/order/history'); ?>"><?php echo __('Shopping List') ?></a></li>
                        <li><a href="<?php echo $block->getUrl('customer/account/edit'); ?>"><?php echo __('Store Create') ?></a></li>
                        <li><a href="<?php echo $block->getUrl('customer/address'); ?>"><?php echo __('Address Book') ?></a></li>
                        <li><a href="<?php echo $block->getUrl('gift-card'); ?>"><?php echo __('Buy Gift Card') ?></a></li>
                        <li><a href="<?php echo $block->getUrl('newsletter/manage'); ?>"><?php echo __('Refer Friends') ?></a></li>
                        <li><a href="<?php echo $block->getUrl('sales/order/history'); ?>"><?php echo __('Orders History') ?></a></li>
                        <li><a <?php echo $dataPostParam ?> href="<?php echo $block->getUrl('customer/account/logout/'); ?>"><?php echo __('Logout') ?></a></li>
                    </ul>
                </div> 
            </div>
        <?php } else{ ?>
        <ul class="actions options header-links-options">
            <?php
            foreach ($this->getLinks() as $link) {
                $html .= $this->renderLink($link);
            }
            //echo $html;
            ?>
            <?php
            /*$custom_links = unserialize($ves->getHeaderCfg('toplinks_settings/custom_links'));
            unset($custom_links['__empty']);
            foreach ($custom_links as $_link) { ?>
            <li class="<?php echo $_link['classes'] ?>" >
                <a href="<?php echo $vesData->filter($_link['link']) ?>" target="<?php echo $_link['target'] ?>"><?php echo $_link['title'] ?></a>
            </li>
            <?php }*/ ?>

            <li><a href="javascript:void(0);" class="signup"><?php echo __('Create an Account'); ?></a></li>
            <li data-label="or" class="authorization-link signin"> <a href="javascript:void(0);"><?php echo __('Sign In'); ?></a></li>

        <?php } ?>

        </ul>
</div>