<fieldset class="fieldset id required" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>"
	<legend class="legend"><span><?php /* @escapeNotVerified */
		echo __('Additional Information') ?></span></legend>
<p>
<div class="field ir id">
	<label for="irid" class="label"><span><?php /* @escapeNotVerified */
		echo __('IR ID') ?></span></label>
	<div class="control">
		<input type="text" name="irid" id="irid" value="" title="<?php /* escapeNotVerified */
		echo __('IR ID') ?>" class="input-text" data-validate="{required:true}">
	</div>
</div>
</p></fieldset>